INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (1,"Mr. Chocolate",4,M,"Brown", "gentle", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (2,"Rowdy", 6, M, "Dark Brown", "rowdy", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (3,"Tabitha", 5, F, "Light Brown", "relaxed", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (4,)
INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (5,)
INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (6,)
INSERT INTO bears (id, name, age, gender, color, temperament, alive)
  VALUES (7,)
INSERT INTO bears (id, age, gender, color, temperament, alive)
  VALUES (8,)
